---
.integration: &integration
  stage: integration
  tags:
    - dcermak-bci-tester
  script:
    - tox -e build
    - tox -e base,init,dotnet,python,node,go,multistage
  after_script:
    - "($CONTAINER_RUNTIME ps -aq|xargs $CONTAINER_RUNTIME rm -f) || :"
    - "($CONTAINER_RUNTIME images -aq|xargs $CONTAINER_RUNTIME rmi -f) || :"
  artifacts:
    when: always
    reports:
      junit: junit_*.xml

stages:
  - test
  - integration

cache:
  paths:
    - .tox

test:
  stage: test
  tags:
    - dcermak-bci-tester
  script:
    - tox -e format -- --check
    - tox -e unit

integration_tests_docker:
  <<: *integration
  variables:
    CONTAINER_RUNTIME: docker

integration_tests_podman:
  <<: *integration
  variables:
    CONTAINER_RUNTIME: podman
