---
.integration: &integration
  stage: integration
  tags:
    - dcermak-bci-tester
  script:
    - tox -e build -- -n auto
    - tox -e all,base,init,dotnet,python,node,go,openjdk,openjdk_devel,minimal,repository,metadata,multistage --parallel
  before_script: []
  after_script:
    - "($CONTAINER_RUNTIME ps -aq|xargs $CONTAINER_RUNTIME rm -f) || :"
    - "($CONTAINER_RUNTIME images -aq|xargs $CONTAINER_RUNTIME rmi -f) || :"
  artifacts:
    when: always
    reports:
      junit: junit_*.xml

stages:
  - test
  - deploy
  - integration

cache:
  paths:
    - .tox

before_script:
  - pip install tox


test_36:
  image: python:3.6
  script:
    - tox -e py36-unit

test_37:
  image: python:3.7
  script:
    - tox -e py37-unit

test_38:
  image: python:3.8
  script:
    - tox -e py38-unit

test_39:
  image: python:3.9
  script:
    - tox -e format -- --check
    - tox -e py39-unit

test_310:
  image: python:3.10
  script:
    - tox -e py310-unit

doc:
  image: python
  script:
    - tox -e doc
  artifacts:
    paths:
      - build/html/

pages:
  stage: deploy
  before_script: []
  dependencies:
    - doc
  script:
    - mkdir public
    - mv build/html/* public/
  artifacts:
    paths:
      - public

integration_tests_docker:
  <<: *integration
  variables:
    TOX_PARALLEL_NO_SPINNER: 1
    CONTAINER_RUNTIME: docker

integration_tests_podman:
  <<: *integration
  variables:
    TOX_PARALLEL_NO_SPINNER: 1
    CONTAINER_RUNTIME: podman

integration_tests_podman_with_bci_repo:
  <<: *integration
  variables:
    TOX_PARALLEL_NO_SPINNER: 1
    CONTAINER_RUNTIME: podman
  script:
    - export BUILD_ID=$(curl -s http://dist.nue.suse.com/ibs/SUSE:/SLE-15-SP3:/Update:/BCI/images/repo/ | grep "\-Build"|head -1| sed 's/.*Build//' | sed 's/-Media.*//')
    - export BCI_DEVEL_REPO="http://dist.nue.suse.com/ibs/SUSE:/SLE-15-SP3:/Update:/BCI/images/repo/SLE-BCI-15-SP3-x86_64-Build${BUILD_ID}-Media1/"
    - tox -e build -- -n auto
    - tox -e all,base,init,dotnet,python,node,go,openjdk,openjdk_devel,minimal,repository,metadata,multistage --parallel

fips:
  stage: integration
  tags:
    - dcermak-bci-tester
  before_script:
    - vagrant box update
  script:
    - vagrant up fips
  after_script:
    - "vagrant destroy -f fips || :"

build_on_registered_system:
  stage: integration
  tags:
    - dcermak-bci-tester
  before_script:
    - vagrant box update
  script:
    - vagrant up registered
  after_script:
    - "vagrant destroy -f registered || :"
