---
.integration: &integration
  stage: integration
  tags:
    - dcermak-bci-tester
  script:
    - tox -e build
    - tox -e base,init,dotnet,python,node,go,openjdk,openjdk-devel
    - tox -e multistage -- -n0
  before_script: []
  after_script:
    - "($CONTAINER_RUNTIME ps -aq|xargs $CONTAINER_RUNTIME rm -f) || :"
    - "($CONTAINER_RUNTIME images -aq|xargs $CONTAINER_RUNTIME rmi -f) || :"
  artifacts:
    when: always
    reports:
      junit: junit_*.xml

stages:
  - test
  - integration

cache:
  paths:
    - .tox

before_script:
  - pip install tox


test_36:
  image: python:3.6
  script:
    - tox -e py36-unit

test_37:
  image: python:3.7
  script:
    - tox -e py37-unit

test_38:
  image: python:3.8
  script:
    - tox -e py38-unit

test_39:
  image: python:3.9
  script:
    - tox -e format -- --check
    - tox -e py39-unit

integration_tests_docker:
  <<: *integration
  variables:
    CONTAINER_RUNTIME: docker

integration_tests_podman:
  <<: *integration
  variables:
    CONTAINER_RUNTIME: podman

fips:
  stage: integration
  tags:
    - dcermak-bci-tester
  before_script: []
  script:
    - vagrant up
  after_script:
    - "vagrant destroy -f || :"
    - "vagrant box remove SLES15-SP3-Vagrant.x86_64 --force --all || :"
