[tool.poetry]
name = "matryoshka-tester"
packages = [
    { include = "matryoshka_tester" }
]
version = "0.1.0"
description = "Tests for the Matryoshka containers"
authors = ["Jean-Philippe Evrard <jean-philippe.evrard@suse.com>"]

[tool.poetry.dependencies]
python = "^3.6.1"
prettytable = "^2.1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
pytest-testinfra = "^6.3.0"
pytest-xdist = {extras = ["psutil"], version = "^2.2.1"}
tox-poetry-installer = {extras = ["poetry"], version = "^0.7.0"}

[tool.poetry.scripts]
m8s-list-containers = 'matryoshka_tester.cmds:list_containers'
m8a-fetch-all-containers = 'matryoshka_tester.cmds:fetch_all_containers'
m8a-fetch-language-containers = 'matryoshka_tester.cmds:fetch_language_containers'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
